### ISSUE TITLE
support for mpt-instruct model [FEATURE]

### ISSUE THREAD

**Issue by NarenZen** [h2oai/h2o-llmstudio#119] opened 2023-05-19 04:45 UTC
### 🚀 Feature

Support for MPT-Instruct model
Hugging Face: mosaicml/mpt-7b-instruct

### Motivation

MPT-Instruct is the SOTA model and is commercially usable.
![Screenshot from 2023-05-19 10-14-49](https://github.com/h2oai/h2o-llmstudio/assets/78342459/7ee974ba-f552-4e60-a256-3373e91d8c33)

**Comment by pascal-pfeiffer** [comment] 2023-05-19 06:36
Is there anything else that prevents you from using MPT other than: https://github.com/h2oai/h2o-llmstudio/issues/117 ?

**Comment by psinger** [comment] 2023-06-05 07:43
Duplicate of https://github.com/h2oai/h2o-llmstudio/issues/103

**Closed by psinger** 2023-06-05 07:43 UTC
Labels: type/feature
