### ISSUE TITLE
[FEATURE] show the full conversation in the validation insights

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/h2o-llmstudio#255] opened 2023-07-06 13:15 UTC
### 🚀 Feature

Currently, only the last prompt + answer is shown in the validation insights. 
For better understanding, we should show the full conversation in case that `parent_id` is used.

**Comment by psinger** [comment] 2023-07-07 07:26
Also add system prompt then

**Comment by psinger** [comment] 2023-07-10 07:57
Duplicate of https://github.com/h2oai/h2o-llmstudio/issues/229 potentially?

**Comment by maxjeblick** [comment] 2023-10-13 10:28
Fixed by #438

**Closed by maxjeblick** 2023-10-13 10:28 UTC
Labels: type/feature
