### ISSUE TITLE
[CODE IMPROVEMENT] Create CICD for UI Testing

### ISSUE THREAD

**Issue by itsmunishbhardwaj** [h2oai/h2o-llmstudio#614] opened 2024-02-12 11:15 UTC
### 🔧 Proposed code refactoring

UI testing is currently manually triggered by me. This issue is to track the progress of add ui tests to the cicd pipeline

**Comment by maxjeblick** [comment] 2024-02-12 14:30
Duplicate of #614
Feel free to assign yourself to #612

**Closed by maxjeblick** 2024-02-12 14:30 UTC
Labels: area/core
