### ISSUE TITLE
[CODE IMPROVEMENT] Deprecate h2oai_pipeline on HF

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#567] opened 2024-01-15 19:40 UTC
### 🔧 Proposed code refactoring

Instead of pushing our custom `h2oai_pipeline.py` to HF, we should use new chat template features.
See example: https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0

**Comment by pascal-pfeiffer** [comment] 2024-01-15 20:30
Duplicate of #551 ?

**Closed** 2024-01-16 19:37 UTC
Labels: area/core
